// Day-type definitions. Edit exercises here.
export const DAY_TYPES = {
  rest: {
    name: 'Rest',
    short: 'Rest',
    type: 'rest',
    accent: 'bg-slate-600',
    text: 'text-slate-300',
    exercises: [],
  },
  upper: {
    name: 'Upper — Strength',
    short: 'Upper',
    type: 'workout',
    accent: 'bg-blue-500',
    text: 'text-blue-300',
    focus: 'strength',
    exercises: [
      'Flat Dumbbell Press',
      'Incline Dumbbell Press',
      'Seated Shoulder Press',
      'Lat Pulldown (heavy)',
      'Seated Row',
      'Face Pulls',
      'Cable Curl / Hammer Curl',
      'Tricep Pushdowns / Extensions',
    ],
  },
  lower: {
    name: 'Lower — Strength',
    short: 'Lower',
    type: 'workout',
    accent: 'bg-red-500',
    text: 'text-red-300',
    focus: 'strength',
    exercises: [
      'Squat or Leg Press',
      'Romanian Deadlift or Deadlift',
      'Leg Curl',
      'Leg Extension',
      'Calves',
      'Core work',
    ],
  },
  push: {
    name: 'Push — Hypertrophy',
    short: 'Push',
    type: 'workout',
    accent: 'bg-amber-500',
    text: 'text-amber-300',
    focus: 'hypertrophy',
    exercises: [
      'Incline DB Press',
      'Flat DB Press',
      'Cable Fly',
      'Seated Shoulder Press',
      'Lateral Raises',
      'Tricep Pushdowns',
      'Overhead Tricep Extensions',
    ],
  },
  pull: {
    name: 'Pull — Hypertrophy',
    short: 'Pull',
    type: 'workout',
    accent: 'bg-emerald-500',
    text: 'text-emerald-300',
    focus: 'hypertrophy',
    exercises: [
      'Lat Pulldown',
      'Seated Row',
      'Face Pulls',
      'Cable Curl',
      'Rope Hammer Curl',
      'Ab work (3 sets)',
    ],
  },
  legs: {
    name: 'Legs — Hypertrophy',
    short: 'Legs',
    type: 'workout',
    accent: 'bg-purple-500',
    text: 'text-purple-300',
    focus: 'hypertrophy',
    exercises: [
      'Leg Press / Hack Squat',
      'Romanian Deadlift',
      'Leg Curl',
      'Leg Extension',
      'Calves',
      'Optional Core',
    ],
  },
};

export const TYPE_ORDER = ['rest', 'upper', 'lower', 'push', 'pull', 'legs'];
